[package]
name = "lens-ts"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
lens-domain = { path = "../lens-domain", version = "0.1.0" }
oxc_allocator = "0.140"
oxc_ast = "0.140"
oxc_ast_visit = "0.140"
oxc_parser = "0.140"
oxc_span = "0.140"
oxc_syntax = "0.140"
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
