//! `analyze co-change` — temporal (logical) coupling from git history.
//!
//! Answers the question a static analyzer cannot: *what else does
//! history say I will have to edit?* Files that keep changing in the same
//! commit are coupled whether or not anything in the code says so — and
//! the pairs with no visible reason to be coupled are the interesting
//! ones.
//!
//! This is the one analyzer with no language support matrix. It reads
//! `git log` and nothing else, so it covers `.toml`, `.md`, workflow
//! YAML, fixtures, and generated files — coupling every AST-based
//! analyzer here is blind to by construction.
//!
//! Paths are emitted in the same repo-root-relative space `hotspot` and
//! `risk` use, so joining a co-change edge against a churn or centrality
//! row is a key lookup rather than a second path normalisation.
//!
//! Limitations, restated in the report itself because this is a metric
//! that is easy to over-read:
//!
//! * A co-change edge is symmetric and says nothing about *why* two
//!   files move together or which one depends on the other. The two
//!   conditional confidences are the closest thing to a direction, and
//!   they are a correlation, not a cause.
//! * Tangled commits inflate support; squash-merge and monorepo
//!   workflows distort what "one change" means. `--max-commit-files` is a
//!   blunt guard against the worst of it, not a fix, and how often it
//!   fired is reported.
//! * A shallow clone reads a truncated history. The report warns on
//!   stderr rather than quietly claiming there is no coupling.
//! * Pathspec scoping cuts both ways: pointing at a subdirectory
//!   restricts the file sets to that subdirectory too, so cross-tree
//!   pairs (`src/` ↔ `docs/`, code ↔ CI config) only appear in a run
//!   whose path covers both.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use lens_domain::{
    CoChangePair, CoChangeReport, CoChangeThresholds, CommitFiles, DEFAULT_MAX_COMMIT_FILES,
    DEFAULT_MIN_CONFIDENCE, DEFAULT_MIN_SUPPORT, compute_cochange,
};
use serde::Serialize;
use tracing::warn;

use super::churn::ChurnScope;
use super::error_from::impl_from_churn_error;
use super::{AnalyzePathFilter, AnalyzeRoots, CompiledPathFilter, OutputFormat, PathFilterError};

/// What the numbers do and do not license, stated in the output because
/// the gap between "these change together" and "these depend on each
/// other" is exactly where an agent would otherwise over-read the
/// result.
const NOTE: &str = "Temporal coupling from git history, not a code dependency: a pair changed \
     together, and nothing here says why or in which direction. `confidence_a_to_b` is \
     P(b changed | a changed) over the counted commits, and it is asymmetric — read both. \
     `lift` guards the metric's usual false positive: at lift near 1 the pair is only as \
     coupled as two files that busy would be by chance, however high its support. Tangled and \
     squashed commits inflate support; commits over --max-commit-files are dropped whole and \
     counted under skipped_commit_count.";

/// Errors raised while running the co-change analyzer.
#[derive(Debug, thiserror::Error)]
pub enum CoChangeError {
    #[error("failed to read {path:?}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    /// `git` is missing or returned a non-zero exit status. The captured
    /// stderr is forwarded so the agent has a useful diagnostic.
    #[error("git failed: {}", stderr.trim_end())]
    Git { stderr: String },
    /// The provided path is not inside any git working tree.
    #[error("{path:?} is not inside a git working tree")]
    NotInGitRepo { path: PathBuf },
    /// A confidence is a probability, so a cut outside `[0.0, 1.0]` can
    /// never be met. Left unchecked it produces an empty report, which
    /// reads as "this history carries no coupling" — the opposite of what
    /// happened. Fail instead of answering a question that was not asked,
    /// the same way `similarity` rejects an unreachable threshold.
    #[error(
        "--min-confidence must be within [0.0, 1.0]; got {value} — no pair's confidence can reach it"
    )]
    MinConfidenceOutOfRange { value: f64 },
    #[error("failed to serialize report: {0}")]
    Serialize(#[from] serde_json::Error),
    #[error(transparent)]
    PathFilter(#[from] PathFilterError),
}

impl_from_churn_error!(CoChangeError);

/// `analyze co-change` flags, and the `[profile.<name>.co-change]` table.
///
/// Written out rather than generated by `analyzer_options!` because the
/// three thresholds carry real clap defaults: `Default` and the
/// `default_value_t` attributes must agree, so both read the same consts
/// from `lens_domain::cochange`.
#[derive(Debug, Clone, clap::Args, serde::Deserialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields, default)]
pub struct CoChangeOptions {
    /// Cap the markdown ranking to the top-N entries. JSON output always
    /// carries the full list.
    #[arg(long)]
    pub top: Option<usize>,
    /// Restrict history to commits in this `--since=` window. Accepts
    /// anything git's approxidate parser does (e.g. `90.days.ago`,
    /// `2024-01-01`). Every count, confidence and lift figure is
    /// computed inside the window.
    #[arg(long)]
    pub since: Option<String>,
    /// Minimum co-change count for a pair to be reported. Below this a
    /// pair is coincidence: two commits is not a pattern, and an empty
    /// report is a better answer than a confident one.
    #[arg(long, default_value_t = DEFAULT_MIN_SUPPORT)]
    pub min_support: u32,
    /// Minimum for a pair's stronger confidence direction. The gate is on
    /// the stronger one on purpose — gating on the weaker would drop the
    /// asymmetric pairs that are the most actionable.
    #[arg(long, default_value_t = DEFAULT_MIN_CONFIDENCE)]
    pub min_confidence: f64,
    /// Commits touching more files than this are dropped whole: a squash
    /// merge or a repo-wide rename would otherwise couple everything to
    /// everything. Also the cost bound, since pair counting is quadratic
    /// in a commit's file count.
    #[arg(long, default_value_t = DEFAULT_MAX_COMMIT_FILES)]
    pub max_commit_files: usize,
}

impl Default for CoChangeOptions {
    fn default() -> Self {
        Self {
            top: None,
            since: None,
            min_support: DEFAULT_MIN_SUPPORT,
            min_confidence: DEFAULT_MIN_CONFIDENCE,
            max_commit_files: DEFAULT_MAX_COMMIT_FILES,
        }
    }
}

/// Stateful co-change runner.
///
/// The default thresholds come from [`CoChangeThresholds::default`], the
/// same consts [`CoChangeOptions`] spells as its `default_value_t`, so an
/// unconfigured analyzer and a bare command line agree.
#[derive(Debug, Clone, Default)]
pub struct CoChangeAnalyzer {
    since: Option<String>,
    top: Option<usize>,
    thresholds: CoChangeThresholds,
    path_filter: AnalyzePathFilter,
}

impl CoChangeAnalyzer {
    pub fn new() -> Self {
        Self::default()
    }

    /// Apply a whole [`CoChangeOptions`] group. The CLI flags and the
    /// `[profile.<name>.co-change]` table are the same type, so this is
    /// the only seam between parsed options and the analyzer.
    pub fn with_options(self, opts: CoChangeOptions) -> Self {
        self.with_top(opts.top)
            .with_since_opt(opts.since)
            .with_min_support(opts.min_support)
            .with_min_confidence(opts.min_confidence)
            .with_max_commit_files(opts.max_commit_files)
    }

    /// Restrict history to commits made in the given git `--since=`
    /// window. Anything git's `approxidate` parser accepts works.
    pub fn with_since(mut self, since: impl Into<String>) -> Self {
        self.since = Some(since.into());
        self
    }

    /// Like [`Self::with_since`] but accepts an `Option`, leaving the
    /// window unchanged when `None` is passed.
    pub fn with_since_opt(mut self, since: Option<String>) -> Self {
        if let Some(s) = since {
            self.since = Some(s);
        }
        self
    }

    /// Cap the markdown report's table to the top-N entries. JSON output
    /// always carries the full list. `None` keeps every row.
    pub fn with_top(mut self, top: Option<usize>) -> Self {
        self.top = top;
        self
    }

    pub fn with_min_support(mut self, min_support: u32) -> Self {
        self.thresholds.min_support = min_support;
        self
    }

    pub fn with_min_confidence(mut self, min_confidence: f64) -> Self {
        self.thresholds.min_confidence = min_confidence;
        self
    }

    pub fn with_max_commit_files(mut self, max_commit_files: usize) -> Self {
        self.thresholds.max_commit_files = max_commit_files;
        self
    }

    pub fn with_only_tests(mut self, only_tests: bool) -> Self {
        self.path_filter = self.path_filter.with_only_tests(only_tests);
        self
    }

    pub fn with_exclude_tests(mut self, exclude_tests: bool) -> Self {
        self.path_filter = self.path_filter.with_exclude_tests(exclude_tests);
        self
    }

    pub fn with_exclude_patterns(mut self, exclude: Vec<String>) -> Self {
        self.path_filter = self.path_filter.with_exclude_patterns(exclude);
        self
    }

    /// Read `roots`' history and produce a co-change report in `format`.
    /// Accepts a single path or several — see [`AnalyzeRoots`]; every root
    /// must sit in the same working tree.
    pub fn analyze(
        &self,
        roots: impl Into<AnalyzeRoots>,
        format: OutputFormat,
    ) -> Result<String, CoChangeError> {
        let confidence = self.thresholds.min_confidence;
        if !(0.0..=1.0).contains(&confidence) {
            return Err(CoChangeError::MinConfidenceOutOfRange { value: confidence });
        }
        let roots = roots.into();
        let scope = ChurnScope::resolve(&roots)?;
        let filter = self.path_filter.compile(scope.repo_root())?;

        let shallow = scope.is_shallow();
        if shallow {
            warn!(
                "shallow clone: `git log` sees a truncated history, so co-change support counts \
                 are lower bounds and pairs whose evidence predates the graft are missing \
                 entirely. Fetch the full history (`git fetch --unshallow`) for a usable report."
            );
        }

        let mut commits = scope.collect_commits(self.since.as_deref())?;
        retain_reportable_paths(&mut commits, &filter, scope.repo_root());
        let report = compute_cochange(&commits, self.thresholds);

        let view = ReportView::new(
            &roots,
            scope.repo_root(),
            self.since.as_deref(),
            shallow,
            self.thresholds,
            &report,
        );
        match format {
            OutputFormat::Json => {
                serde_json::to_string_pretty(&view).map_err(CoChangeError::Serialize)
            }
            OutputFormat::Md => Ok(format_markdown(&view, self.top)),
        }
    }
}

/// Drop paths a report cannot act on: those the path filter excludes, and
/// those no longer in the working tree.
///
/// The existence gate is the same call `hotspot` makes by joining against
/// walked source files: an agent about to edit a file cannot go read a
/// partner that was deleted three months ago, and history is full of
/// them. Each distinct path is decided once, so the `stat` cost is per
/// file rather than per mention.
///
/// Shared with [`super::hidden_coupling`], which subtracts the static
/// graph from exactly this history: the two analyzers have to agree on
/// which commits and which paths are in play, or a pair reported as
/// co-changing by one is invisible to the other.
pub(super) fn retain_reportable_paths(
    commits: &mut [CommitFiles],
    filter: &CompiledPathFilter,
    repo_root: &Path,
) {
    let mut decided: BTreeMap<String, bool> = BTreeMap::new();
    for commit in commits.iter() {
        for file in &commit.files {
            if !decided.contains_key(file) {
                let keep = filter.includes_relative(file) && repo_root.join(file).exists();
                decided.insert(file.clone(), keep);
            }
        }
    }
    for commit in commits {
        commit
            .files
            .retain(|file| decided.get(file).copied().unwrap_or(false));
    }
}

#[derive(Debug, Serialize)]
struct ReportView<'a> {
    target: String,
    repo_root: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    since: Option<&'a str>,
    note: &'static str,
    /// Set when `git log` is reading a truncated history, so a consumer
    /// of the JSON sees the same caveat the stderr warning carries.
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    shallow_clone: bool,
    thresholds: ThresholdsView,
    commit_count: usize,
    skipped_commit_count: usize,
    file_count: usize,
    candidate_pair_count: usize,
    pair_count: usize,
    pairs: Vec<PairView<'a>>,
}

impl<'a> ReportView<'a> {
    fn new(
        roots: &AnalyzeRoots,
        repo_root: &Path,
        since: Option<&'a str>,
        shallow_clone: bool,
        thresholds: CoChangeThresholds,
        report: &'a CoChangeReport,
    ) -> Self {
        Self {
            target: roots.display(),
            repo_root: repo_root.display().to_string(),
            since,
            note: NOTE,
            shallow_clone,
            thresholds: ThresholdsView {
                min_support: thresholds.min_support,
                min_confidence: thresholds.min_confidence,
                max_commit_files: thresholds.max_commit_files,
            },
            commit_count: report.commit_count,
            skipped_commit_count: report.skipped_commit_count,
            file_count: report.file_count,
            candidate_pair_count: report.candidate_pair_count,
            pair_count: report.pairs.len(),
            pairs: report.pairs.iter().map(PairView::from).collect(),
        }
    }
}

#[derive(Debug, Serialize)]
struct ThresholdsView {
    min_support: u32,
    min_confidence: f64,
    max_commit_files: usize,
}

#[derive(Debug, Serialize)]
struct PairView<'a> {
    a: &'a str,
    b: &'a str,
    cochanges: u32,
    commits_a: u32,
    commits_b: u32,
    confidence_a_to_b: f64,
    confidence_b_to_a: f64,
    lift: f64,
    score: f64,
    last_cochange: &'a str,
    last_cochange_commits_ago: usize,
}

impl<'a> From<&'a CoChangePair> for PairView<'a> {
    fn from(p: &'a CoChangePair) -> Self {
        Self {
            a: p.a.as_str(),
            b: p.b.as_str(),
            cochanges: p.cochanges,
            commits_a: p.commits_a,
            commits_b: p.commits_b,
            confidence_a_to_b: p.confidence_a_to_b,
            confidence_b_to_a: p.confidence_b_to_a,
            lift: p.lift,
            score: p.score,
            last_cochange: p.last_cochange.as_str(),
            last_cochange_commits_ago: p.last_cochange_commits_ago,
        }
    }
}

const DEFAULT_TOP: usize = 20;

fn format_markdown(view: &ReportView<'_>, top: Option<usize>) -> String {
    let scope = view
        .since
        .map_or_else(String::new, |s| format!(", since {s}"));
    let mut out = format!(
        "# Co-change report: {} ({} pair(s) over {} commit(s){scope})\n",
        view.target, view.pair_count, view.commit_count,
    );
    let _ = writeln!(&mut out, "\n{}", view.note);
    if view.shallow_clone {
        out.push_str(
            "\n**Shallow clone**: the log is truncated, so every support count below is a lower \
             bound and pairs whose evidence predates the graft are missing. Run \
             `git fetch --unshallow` before trusting this report.\n",
        );
    }

    let _ = writeln!(
        &mut out,
        "\n## Summary\n\
         - commits: {} counted, {} skipped over `--max-commit-files {}`\n\
         - files: {}\n\
         - pairs: {} reported of {} that co-changed at least once\n\
         - thresholds: support >= {}, max confidence >= {:.2}",
        view.commit_count,
        view.skipped_commit_count,
        view.thresholds.max_commit_files,
        view.file_count,
        view.pair_count,
        view.candidate_pair_count,
        view.thresholds.min_support,
        view.thresholds.min_confidence,
    );

    if view.pairs.is_empty() {
        out.push_str(if view.commit_count == 0 {
            "\n_No commits matched._\n"
        } else {
            "\n_No pair met the thresholds._\n"
        });
        return out;
    }

    let limit = top.unwrap_or(DEFAULT_TOP);
    let _ = writeln!(
        &mut out,
        "\n## Top {limit} co-changing pairs (support × max confidence)\n"
    );
    let _ = writeln!(
        &mut out,
        "| a | b | co | a→b | b→a | lift | commits_a | commits_b | last |"
    );
    let _ = writeln!(
        &mut out,
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |"
    );
    for p in view.pairs.iter().take(limit) {
        let _ = writeln!(
            &mut out,
            "| {} | {} | {} | {:.2} | {:.2} | {:.2} | {} | {} | {} ({} ago) |",
            p.a,
            p.b,
            p.cochanges,
            p.confidence_a_to_b,
            p.confidence_b_to_a,
            p.lift,
            p.commits_a,
            p.commits_b,
            p.last_cochange,
            p.last_cochange_commits_ago,
        );
    }
    let overflow = view.pairs.len().saturating_sub(limit);
    if overflow > 0 {
        let _ = writeln!(
            &mut out,
            "\n+{overflow} more pair(s) not shown (raise `--top`; JSON carries every row)."
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::{run_git, write_file};
    use rstest::rstest;

    fn init_repo(dir: &Path) {
        run_git(dir, &["init", "-q", "-b", "main"]);
        run_git(dir, &["config", "user.email", "test@example.com"]);
        run_git(dir, &["config", "user.name", "Test"]);
    }

    /// Commit `files` (path, contents) as one change.
    fn commit(dir: &Path, message: &str, files: &[(&str, &str)]) {
        for (path, contents) in files {
            write_file(dir, path, contents);
        }
        run_git(dir, &["add", "-A"]);
        run_git(dir, &["commit", "-q", "-m", message]);
    }

    /// A history where `src/api.rs` and `tests/api.rs` always move
    /// together, `src/lone.rs` moves on its own, and every file still
    /// exists at the end.
    fn init_coupled_history(dir: &Path) {
        init_repo(dir);
        for i in 0..4 {
            commit(
                dir,
                &format!("paired {i}"),
                &[
                    ("src/api.rs", &format!("pub fn api() -> u8 {{ {i} }}\n")),
                    ("tests/api.rs", &format!("// case {i}\n")),
                ],
            );
        }
        for i in 0..2 {
            commit(
                dir,
                &format!("lone {i}"),
                &[("src/lone.rs", &format!("pub fn lone() -> u8 {{ {i} }}\n"))],
            );
        }
    }

    fn json(analyzer: &CoChangeAnalyzer, dir: &Path) -> serde_json::Value {
        let out = analyzer.analyze(dir, OutputFormat::Json).unwrap();
        serde_json::from_str(&out).unwrap()
    }

    #[test]
    fn json_report_ranks_the_coupled_pair_and_states_its_arithmetic() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let parsed = json(&CoChangeAnalyzer::new(), dir.path());

        assert_eq!(parsed["commit_count"], 6);
        assert_eq!(parsed["file_count"], 3);
        let pairs = parsed["pairs"].as_array().unwrap();
        assert_eq!(pairs.len(), 1, "got {parsed}");
        let pair = &pairs[0];
        assert_eq!(pair["a"], "src/api.rs");
        assert_eq!(pair["b"], "tests/api.rs");
        assert_eq!(pair["cochanges"], 4);
        assert_eq!(pair["commits_a"], 4);
        assert_eq!(pair["commits_b"], 4);
        assert!((pair["confidence_a_to_b"].as_f64().unwrap() - 1.0).abs() < 1e-9);
        assert!((pair["confidence_b_to_a"].as_f64().unwrap() - 1.0).abs() < 1e-9);
        // (4 * 6) / (4 * 4) = 1.5
        assert!((pair["lift"].as_f64().unwrap() - 1.5).abs() < 1e-9);
        assert_eq!(pair["last_cochange_commits_ago"], 2);
        assert!(
            pair["last_cochange"].as_str().unwrap().len() == 10,
            "expected a YYYY-MM-DD date, got {pair}",
        );
    }

    /// The whole point of the analyzer: a `.toml` / `.md` pair no
    /// AST-based analyzer can see at all.
    #[test]
    fn non_source_files_are_covered() {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        for i in 0..3 {
            commit(
                dir.path(),
                &format!("bump {i}"),
                &[
                    ("Cargo.toml", &format!("version = \"0.0.{i}\"\n")),
                    ("CHANGELOG.md", &format!("# 0.0.{i}\n")),
                ],
            );
        }
        let parsed = json(&CoChangeAnalyzer::new(), dir.path());
        let pairs = parsed["pairs"].as_array().unwrap();
        assert_eq!(pairs.len(), 1, "got {parsed}");
        assert_eq!(pairs[0]["a"], "CHANGELOG.md");
        assert_eq!(pairs[0]["b"], "Cargo.toml");
    }

    /// A rename must not split a pair's support in two — without the
    /// rename map this pair sits at 2 co-changes and the default
    /// `--min-support` hides it.
    #[test]
    fn a_rename_mid_history_keeps_one_pair() {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        for i in 0..2 {
            commit(
                dir.path(),
                &format!("before {i}"),
                &[
                    ("src/old.rs", &format!("pub fn f() -> u8 {{ {i} }}\n")),
                    ("src/other.rs", &format!("pub fn g() -> u8 {{ {i} }}\n")),
                ],
            );
        }
        run_git(dir.path(), &["mv", "src/old.rs", "src/new.rs"]);
        run_git(dir.path(), &["commit", "-q", "-m", "rename"]);
        for i in 0..2 {
            commit(
                dir.path(),
                &format!("after {i}"),
                &[
                    ("src/new.rs", &format!("pub fn f() -> u16 {{ {i} }}\n")),
                    ("src/other.rs", &format!("pub fn g() -> u16 {{ {i} }}\n")),
                ],
            );
        }

        let parsed = json(&CoChangeAnalyzer::new(), dir.path());
        let pairs = parsed["pairs"].as_array().unwrap();
        assert_eq!(pairs.len(), 1, "got {parsed}");
        assert_eq!(pairs[0]["a"], "src/new.rs");
        assert_eq!(pairs[0]["b"], "src/other.rs");
        assert_eq!(
            pairs[0]["cochanges"], 4,
            "the rename split the pair: {parsed}"
        );
    }

    #[test]
    fn a_commit_over_the_size_cap_is_dropped_and_counted() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        // One squash-shaped commit touching everything at once.
        commit(
            dir.path(),
            "squash",
            &[
                ("src/api.rs", "pub fn api() -> u8 { 9 }\n"),
                ("tests/api.rs", "// squashed\n"),
                ("src/lone.rs", "pub fn lone() -> u8 { 9 }\n"),
            ],
        );

        let capped = json(
            &CoChangeAnalyzer::new().with_max_commit_files(2),
            dir.path(),
        );
        assert_eq!(capped["skipped_commit_count"], 1);
        assert_eq!(capped["commit_count"], 6);
        assert!(
            capped["pairs"]
                .as_array()
                .unwrap()
                .iter()
                .all(|p| p["a"] != "src/lone.rs" && p["b"] != "src/lone.rs"),
            "the tangled commit still coupled the lone file: {capped}",
        );

        let uncapped = json(&CoChangeAnalyzer::new(), dir.path());
        assert_eq!(uncapped["skipped_commit_count"], 0);
        assert_eq!(uncapped["commit_count"], 7);
    }

    #[test]
    fn thresholds_gate_the_report_and_the_candidate_count_says_so() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let strict = json(&CoChangeAnalyzer::new().with_min_support(5), dir.path());
        assert_eq!(strict["pair_count"], 0);
        assert_eq!(strict["candidate_pair_count"], 1);

        let loose = json(
            &CoChangeAnalyzer::new().with_min_confidence(0.0),
            dir.path(),
        );
        assert_eq!(loose["pair_count"], 1);
    }

    #[test]
    fn thresholds_are_reported_so_an_empty_report_is_readable() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let parsed = json(
            &CoChangeAnalyzer::new()
                .with_min_support(7)
                .with_min_confidence(0.75)
                .with_max_commit_files(11),
            dir.path(),
        );
        assert_eq!(parsed["thresholds"]["min_support"], 7);
        assert!((parsed["thresholds"]["min_confidence"].as_f64().unwrap() - 0.75).abs() < 1e-9);
        assert_eq!(parsed["thresholds"]["max_commit_files"], 11);
    }

    #[test]
    fn a_since_window_scopes_the_history() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let parsed = json(
            &CoChangeAnalyzer::new().with_since("2099-01-01"),
            dir.path(),
        );
        assert_eq!(parsed["commit_count"], 0);
        assert_eq!(parsed["since"], "2099-01-01");
        assert!(parsed["pairs"].as_array().unwrap().is_empty());
    }

    #[test]
    fn since_option_is_applied_when_present() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let parsed = json(
            &CoChangeAnalyzer::new().with_since_opt(Some("2099-01-01".to_owned())),
            dir.path(),
        );
        assert_eq!(parsed["since"], "2099-01-01");
    }

    /// A partner that no longer exists cannot be read or edited, so it is
    /// dropped the same way `hotspot` drops churn-only paths.
    #[test]
    fn a_deleted_file_is_not_reported_as_a_partner() {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        for i in 0..4 {
            commit(
                dir.path(),
                &format!("paired {i}"),
                &[
                    ("src/live.rs", &format!("pub fn a() -> u8 {{ {i} }}\n")),
                    ("src/doomed.rs", &format!("pub fn b() -> u8 {{ {i} }}\n")),
                ],
            );
        }
        std::fs::remove_file(dir.path().join("src/doomed.rs")).unwrap();
        run_git(dir.path(), &["add", "-A"]);
        run_git(dir.path(), &["commit", "-q", "-m", "drop doomed"]);

        let parsed = json(&CoChangeAnalyzer::new(), dir.path());
        assert!(
            parsed["pairs"].as_array().unwrap().is_empty(),
            "a deleted partner leaked into the report: {parsed}",
        );
    }

    #[test]
    fn path_filters_apply_to_the_history() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());

        let excluded = json(
            &CoChangeAnalyzer::new().with_exclude_tests(true),
            dir.path(),
        );
        assert!(
            excluded["pairs"].as_array().unwrap().is_empty(),
            "exclude-tests must drop the tests/ half of the pair: {excluded}",
        );

        let globbed = json(
            &CoChangeAnalyzer::new().with_exclude_patterns(vec!["tests/**".to_owned()]),
            dir.path(),
        );
        assert!(
            globbed["pairs"].as_array().unwrap().is_empty(),
            "an --exclude glob must reach the history too: {globbed}",
        );

        let only = json(&CoChangeAnalyzer::new().with_only_tests(true), dir.path());
        assert_eq!(only["file_count"], 1, "got {only}");
    }

    /// A subdirectory target keys on repo-relative paths, which is what
    /// makes a co-change edge joinable against a `hotspot` or `risk` row.
    #[test]
    fn a_subdirectory_target_keeps_repo_relative_paths() {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        for i in 0..3 {
            commit(
                dir.path(),
                &format!("paired {i}"),
                &[
                    (
                        "crates/app/src/a.rs",
                        &format!("pub fn a() -> u8 {{ {i} }}\n"),
                    ),
                    (
                        "crates/app/src/b.rs",
                        &format!("pub fn b() -> u8 {{ {i} }}\n"),
                    ),
                    ("docs/notes.md", &format!("# {i}\n")),
                ],
            );
        }
        let out = CoChangeAnalyzer::new()
            .analyze(dir.path().join("crates/app"), OutputFormat::Json)
            .unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        let pairs = parsed["pairs"].as_array().unwrap();
        assert_eq!(pairs.len(), 1, "got {parsed}");
        assert_eq!(pairs[0]["a"], "crates/app/src/a.rs");
        assert_eq!(pairs[0]["b"], "crates/app/src/b.rs");
        assert!(
            pairs
                .iter()
                .all(|p| p["a"] != "docs/notes.md" && p["b"] != "docs/notes.md"),
            "the pathspec must scope the file sets too: {parsed}",
        );
    }

    #[test]
    fn markdown_report_carries_the_summary_the_note_and_the_table() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let md = CoChangeAnalyzer::new()
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains("# Co-change report:"), "got {md}");
        assert!(md.contains("not a code dependency"), "got {md}");
        assert!(md.contains("## Summary"), "got {md}");
        assert!(md.contains("| src/api.rs | tests/api.rs |"), "got {md}");
    }

    #[test]
    fn markdown_top_caps_the_table_and_says_what_is_left() {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        for i in 0..3 {
            commit(
                dir.path(),
                &format!("trio {i}"),
                &[
                    ("src/a.rs", &format!("pub fn a() -> u8 {{ {i} }}\n")),
                    ("src/b.rs", &format!("pub fn b() -> u8 {{ {i} }}\n")),
                    ("src/c.rs", &format!("pub fn c() -> u8 {{ {i} }}\n")),
                ],
            );
        }
        let md = CoChangeAnalyzer::new()
            .with_top(Some(1))
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains("## Top 1 co-changing pairs"), "got {md}");
        assert_eq!(
            md.lines().filter(|l| l.starts_with("| src/")).count(),
            1,
            "got {md}",
        );
        assert!(md.contains("+2 more pair(s) not shown"), "got {md}");
    }

    /// A report that fit under the cap must not carry an overflow line:
    /// "+0 more" reads as truncation that never happened, and a caveat
    /// that does not apply costs context without saying anything.
    #[test]
    fn markdown_says_nothing_about_overflow_when_nothing_was_capped() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let md = CoChangeAnalyzer::new()
            .with_top(Some(20))
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains("| src/api.rs | tests/api.rs |"), "got {md}");
        assert!(!md.contains("more pair(s) not shown"), "got {md}");
    }

    #[rstest]
    #[case::no_commits_at_all("2099-01-01", "_No commits matched._")]
    #[case::nothing_met_the_thresholds("2000-01-01", "_No pair met the thresholds._")]
    fn an_empty_markdown_report_says_which_kind_of_empty_it_is(
        #[case] since: &str,
        #[case] expected: &str,
    ) {
        let dir = tempfile::tempdir().unwrap();
        init_repo(dir.path());
        commit(dir.path(), "solo", &[("src/a.rs", "pub fn a() {}\n")]);
        let md = CoChangeAnalyzer::new()
            .with_since(since)
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains(expected), "got {md}");
    }

    #[test]
    fn a_shallow_clone_is_flagged_in_the_report() {
        let origin = tempfile::tempdir().unwrap();
        init_coupled_history(origin.path());
        let clone = tempfile::tempdir().unwrap();
        let target = clone.path().join("shallow");
        run_git(
            clone.path(),
            &[
                "clone",
                "-q",
                "--depth",
                "1",
                &format!("file://{}", origin.path().display()),
                &target.display().to_string(),
            ],
        );

        let parsed = json(&CoChangeAnalyzer::new(), &target);
        assert_eq!(parsed["shallow_clone"], true, "got {parsed}");
        let md = CoChangeAnalyzer::new()
            .analyze(&target, OutputFormat::Md)
            .unwrap();
        assert!(md.contains("**Shallow clone**"), "got {md}");
    }

    /// The flag is absent, not `false`, on an ordinary clone: a caveat
    /// that does not apply costs context without saying anything.
    #[test]
    fn a_full_clone_carries_no_shallow_flag() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let parsed = json(&CoChangeAnalyzer::new(), dir.path());
        assert!(parsed.get("shallow_clone").is_none(), "got {parsed}");
        let md = CoChangeAnalyzer::new()
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(!md.contains("Shallow clone"), "got {md}");
    }

    #[test]
    fn target_directory_outside_git_errors() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "lone.rs", "fn x() {}\n");
        let err = CoChangeAnalyzer::new()
            .analyze(dir.path(), OutputFormat::Json)
            .unwrap_err();
        assert!(matches!(err, CoChangeError::NotInGitRepo { .. }), "{err:?}");
    }

    #[test]
    fn missing_path_surfaces_io_error() {
        let err = CoChangeAnalyzer::new()
            .analyze(Path::new("/definitely/does/not/exist"), OutputFormat::Json)
            .unwrap_err();
        assert!(matches!(err, CoChangeError::Io { .. }), "{err:?}");
    }

    /// An unreachable cut would produce an empty report, which reads as
    /// "no coupling here" — a different answer from "you asked for
    /// something impossible". The check runs before git does, so it holds
    /// outside a working tree too.
    #[rstest]
    #[case::above_one(1.5)]
    #[case::negative(-0.1)]
    fn an_unreachable_min_confidence_is_rejected(#[case] value: f64) {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let err = CoChangeAnalyzer::new()
            .with_min_confidence(value)
            .analyze(dir.path(), OutputFormat::Json)
            .unwrap_err();
        let CoChangeError::MinConfidenceOutOfRange { value: reported } = err else {
            panic!("expected MinConfidenceOutOfRange, got {err:?}");
        };
        assert!((reported - value).abs() < f64::EPSILON);
    }

    #[rstest]
    #[case::zero(0.0)]
    #[case::one(1.0)]
    fn the_confidence_bounds_themselves_are_accepted(#[case] value: f64) {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        assert!(
            CoChangeAnalyzer::new()
                .with_min_confidence(value)
                .analyze(dir.path(), OutputFormat::Json)
                .is_ok(),
        );
    }

    #[test]
    fn an_invalid_exclude_glob_surfaces_a_path_filter_error() {
        let dir = tempfile::tempdir().unwrap();
        init_coupled_history(dir.path());
        let err = CoChangeAnalyzer::new()
            .with_exclude_patterns(vec!["[".to_owned()])
            .analyze(dir.path(), OutputFormat::Json)
            .unwrap_err();
        assert!(matches!(err, CoChangeError::PathFilter(_)), "{err:?}");
    }

    #[rstest]
    #[case::io(
        CoChangeError::Io {
            path: PathBuf::from("/tmp/x"),
            source: std::io::Error::new(std::io::ErrorKind::NotFound, "missing"),
        },
        &["/tmp/x", "missing", "failed to read"],
    )]
    #[case::git(
        CoChangeError::Git { stderr: "fatal: not a git repo\n".to_owned() },
        &["fatal: not a git repo"],
    )]
    #[case::not_in_git_repo(
        CoChangeError::NotInGitRepo { path: PathBuf::from("/tmp/lonely") },
        &["/tmp/lonely", "not inside a git working tree"],
    )]
    #[case::min_confidence_out_of_range(
        CoChangeError::MinConfidenceOutOfRange { value: 1.5 },
        &["--min-confidence", "1.5", "[0.0, 1.0]"],
    )]
    fn error_display_carries_the_diagnostic(#[case] err: CoChangeError, #[case] needles: &[&str]) {
        let msg = err.to_string();
        for needle in needles {
            assert!(msg.contains(needle), "missing {needle} in {msg}");
        }
        assert!(!msg.ends_with('\n'), "trailing newline in {msg}");
    }
}
