//! `analyze single-impl` — traits and interfaces with at most one
//! production implementor.
//!
//! An abstraction is a promise that callers will not care which
//! implementation they get. With exactly one production implementor
//! that promise costs indirection on every read — the agent resolves
//! the trait, then the impl, to find the one body that was always going
//! to run — and buys nothing until a second implementor arrives. Such a
//! declaration is `analyze single-use`'s philosophy lifted from
//! functions to abstractions: one user is a reason to consider the
//! concrete type, stated as a candidate, never a verdict. The row
//! itself says when the trade is deliberate: a test implementor is a
//! mock seam, `dyn` references are dynamic dispatch, and a public
//! declaration invites implementors this analyzer cannot see.
//!
//! The census is per language:
//!
//! - **Rust**: implementors are `impl Trait for Type` blocks, matched
//!   to in-tree `trait` declarations by the trait path's trailing
//!   identifier. An `impl fmt::Display for Foo` therefore counts only
//!   if a trait named `Display` is declared in the analyzed tree —
//!   out-of-tree traits never produce rows — and a same-named in-tree
//!   trait can only inflate an implementor count, never deflate it
//!   (the shared-name caveat marks those rows).
//! - **Go**: satisfaction is structural, so implementors are in-tree
//!   types whose method sets cover the interface by name and
//!   parameter count — the same approximation `analyze unreachable`
//!   and `analyze visibility` use, which both over- and under-counts.
//!   Zero-method interfaces match every type and are skipped. An
//!   interface satisfied only by std or third-party types reads as
//!   unimplemented; the no-production-implementor section says so.
//!
//! A raw-name scan counts where each candidate's bare name is written
//! outside its declaration and its implementors' blocks — bounds,
//! `dyn`/`impl Trait` positions, imports, derives. The count measures
//! what removal costs, not whether it is right; `dyn` mentions are
//! counted separately because they name the one capability a concrete
//! type cannot replace without restructuring.
//!
//! TypeScript and Python are not judged: neither adapter extracts
//! abstraction declarations.
//!
//! # Schema history
//!
//! * `schema_version: 1` — initial shape.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;
use std::path::Path;

use serde::Serialize;

use lens_domain::{SyntaxFact, TraitDeclShape, TraitImplShape, VisibilityShape};

use super::call_graph::model::{GraphLanguage, NodeVisibility};
use super::call_graph::{CallGraph, CallGraphBuilder, delegate_call_graph_builders};
use super::options::analyzer_options;
use super::runner::render_report;
use super::unreachable::identifiers;
use super::{AnalyzeRoots, AnalyzerError, OutputFormat, SourceLang};

const SCHEMA_VERSION: u32 = 1;

/// Markdown listing cap when `--top` is not given. JSON always carries
/// every finding.
const DEFAULT_TOP: usize = 20;

/// Implementor names listed inline on a row before the rest are rolled
/// into a count.
const IMPLEMENTORS_PER_ROW: usize = 3;

const NOTE: &str = "Each row is a trait or interface declared in the analyzed tree with at most \
     one production implementor. One implementor is a candidate to replace the abstraction with \
     the concrete type — a candidate, not a verdict: the row says when the indirection is \
     deliberate (a test implementor is a mock seam, `dyn` references are dynamic dispatch, a \
     public declaration invites implementors outside the analyzed tree). Rust implementors are \
     `impl Trait for Type` blocks matched by the trait path's trailing identifier, so a \
     same-named in-tree trait can inflate a count, never deflate it. Go implementors are in-tree \
     types whose method sets cover the interface by name and parameter count — a structural \
     approximation that both over- and under-counts, and an interface satisfied only by \
     out-of-tree types reads as unimplemented. The reference count is bare-name occurrences \
     outside the declaration and its implementors' blocks (bounds, `impl Trait` positions, \
     imports, derives): it measures what removal costs, not whether it is right. An \
     implementation generated by a macro produces no impl block this census can see — a row \
     whose name sits on an `impl … for …` line outside every known block carries that caveat, \
     and its implementor count is a lower bound.";

analyzer_options! {
    /// `analyze single-impl` flags, and the `[profile.<name>.single-impl]`
    /// table.
    pub struct SingleImplOptions {
        @shared(ranking);
    }
}

/// Analyzer entry point for `analyze single-impl`.
#[derive(Debug, Default, Clone)]
pub struct SingleImplAnalyzer {
    builder: CallGraphBuilder,
    top: Option<usize>,
}

impl SingleImplAnalyzer {
    /// Apply a whole [`SingleImplOptions`] group. The CLI flags and the
    /// `[profile.<name>.single-impl]` table are the same type, so this
    /// is the only seam between parsed options and the analyzer.
    pub fn with_options(self, opts: SingleImplOptions) -> Self {
        self.with_top(opts.top)
    }

    pub fn new() -> Self {
        Self::default()
    }

    delegate_call_graph_builders! {
        builder,
        /// Accepted for CLI uniformity. Declarations are classified by
        /// their own test scope, so this only changes which functions
        /// the Go method-set census sees.
        only_tests,
        /// Drops test files. Test implementors then stop being visible,
        /// so the mock-seam caveat cannot fire.
        exclude_tests,
    }

    /// Cap each markdown section to the top-N entries. JSON output
    /// always carries every finding.
    pub fn with_top(mut self, top: Option<usize>) -> Self {
        self.top = top;
        self
    }

    pub fn analyze(
        &self,
        roots: impl Into<AnalyzeRoots>,
        format: OutputFormat,
    ) -> Result<String, AnalyzerError> {
        let roots = roots.into();
        // The graph supplies per-file module paths and test
        // classification, and the Go census reads its method nodes.
        let graph = self.builder.clone().build(&roots)?;
        let inventory = Inventory::collect(&self.builder, &roots, &graph)?;
        let scan = UsageScan::run(&self.builder, &roots, &inventory)?;
        let report = Report::build(&roots, &graph, inventory, &scan);
        render_report(&report, format, || format_markdown(&report, self.top))
    }
}

/// A reason the single-implementor claim, or the removal, is weaker for
/// this row than its presence suggests. Caveats demote; they never
/// remove a row from the JSON.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
enum Caveat {
    /// Visible beyond its own module or package: an implementor outside
    /// the analyzed tree can exist.
    WiderThanPrivate,
    /// A test-scoped implementor exists: the abstraction may be a
    /// deliberate mock seam, and removing it moves those tests onto the
    /// concrete type.
    TestImplementors,
    /// `dyn Trait` is written somewhere: the declaration is dynamically
    /// dispatched, which a concrete type cannot replace without
    /// restructuring (Rust only).
    DynDispatch,
    /// An `impl … Name … for …` line outside every known block names
    /// it — typically a macro body generating implementations this
    /// census cannot see, so the implementor count is a lower bound.
    MacroImplPattern,
    /// Several in-tree declarations share this name, so the census may
    /// have attributed implementors to the wrong one.
    SharedName,
}

impl Caveat {
    fn as_str(self) -> &'static str {
        match self {
            Self::WiderThanPrivate => "visible outside its module",
            Self::TestImplementors => "a test implementor exists (mock seam)",
            Self::DynDispatch => "`dyn`-dispatched",
            Self::MacroImplPattern => "an `impl … for …` line names it (a macro may implement it)",
            Self::SharedName => "several in-tree declarations share the name",
        }
    }
}

/// One reported abstraction.
#[derive(Debug, Clone, Serialize)]
struct AbstractionEntry {
    /// `"trait"` (Rust) or `"interface"` (Go).
    kind: &'static str,
    display_name: String,
    qualified_name: String,
    file: String,
    start_line: usize,
    end_line: usize,
    visibility: NodeVisibility,
    /// Directly declared methods.
    method_count: usize,
    /// Implementing types with production evidence, sorted. `?` stands
    /// for a Rust self type that is not a plain path.
    production_implementors: Vec<String>,
    /// Implementing types seen only in test scope.
    test_implementor_count: usize,
    /// Bare-name occurrences outside the declaration and its
    /// implementors' blocks, minus the `dyn` ones below.
    reference_count: usize,
    /// Occurrences immediately preceded by a `dyn` token.
    dyn_reference_count: usize,
    /// Occurrences on an `impl … for …`-shaped line outside every
    /// known block — the macro-generated-implementation tell.
    impl_reference_count: usize,
    /// Why this row is weaker than its presence suggests, sorted.
    caveats: Vec<Caveat>,
}

/// What was examined and skipped, so the counts have a denominator.
#[derive(Debug, Default, Serialize)]
struct Audit {
    /// Rust and Go files whose declarations were inventoried.
    file_count: usize,
    /// Files the inventory pass could not parse (the graph skips those
    /// files too, so nothing else saw them either).
    parse_skipped_file_count: usize,
    /// Declarations in test scope: test scaffolding, not production
    /// abstractions, so never rows.
    test_declaration_count: usize,
    /// Go interfaces with zero declared methods: structurally satisfied
    /// by every type, so no census is possible.
    empty_interface_count: usize,
}

/// Production-implementor histogram over every judged declaration —
/// what "normal" looks like in this tree, so a single-impl verdict has
/// a base rate next to it.
#[derive(Debug, Default, Serialize)]
struct ImplementorDistribution {
    zero: usize,
    one: usize,
    two: usize,
    three_plus: usize,
}

#[derive(Debug, Serialize)]
struct Report {
    schema_version: u32,
    root: String,
    language: &'static str,
    note: &'static str,
    audit: Audit,
    /// Judged declarations (non-test, non-empty), before the ≤1 cut.
    declaration_count: usize,
    distribution: ImplementorDistribution,
    /// Declarations with at most one production implementor, strongest
    /// first.
    findings: Vec<AbstractionEntry>,
}

/// One inventoried declaration with its file and census results.
struct DeclRecord {
    shape: TraitDeclShape,
    file: String,
    kind: &'static str,
    production_implementors: BTreeSet<String>,
    test_implementors: BTreeSet<String>,
    /// Spans the usage scan must not count: the declaration itself and
    /// every matched implementor block, as `(file, start, end)`.
    allowed: Vec<(String, usize, usize)>,
}

/// Everything the two source passes produce.
struct Inventory {
    decls: Vec<DeclRecord>,
    audit: Audit,
}

impl Inventory {
    fn collect(
        builder: &CallGraphBuilder,
        roots: &AnalyzeRoots,
        graph: &CallGraph,
    ) -> Result<Self, AnalyzerError> {
        // Module and test classification per file, from the graph's own
        // scan. A file without functions gets no module (its qualified
        // names fall back to the bare name) and counts as production.
        let mut module_of: HashMap<&str, &str> = HashMap::new();
        let mut file_all_test: HashMap<&str, bool> = HashMap::new();
        for node in &graph.nodes {
            module_of.entry(node.file.as_str()).or_insert(&node.module);
            let all_test = file_all_test.entry(node.file.as_str()).or_insert(true);
            *all_test &= node.is_test;
        }

        let mut audit = Audit::default();
        let mut decls: Vec<DeclRecord> = Vec::new();
        let mut rust_impls: Vec<(String, TraitImplShape)> = Vec::new();
        builder.visit_source_texts(roots, |file, source| {
            let module = module_of.get(file).copied().unwrap_or("");
            let file_is_test = file_all_test.get(file).copied().unwrap_or(false);
            match SourceLang::from_path(Path::new(file)) {
                Some(SourceLang::Rust) => {
                    audit.file_count += 1;
                    let Ok((file_decls, file_impls)) =
                        lens_rust::extract_trait_shapes_with_module(source, module)
                    else {
                        audit.parse_skipped_file_count += 1;
                        return;
                    };
                    for mut shape in file_decls {
                        shape.is_test |= file_is_test;
                        decls.push(DeclRecord::new(shape, file, "trait"));
                    }
                    for mut shape in file_impls {
                        shape.is_test |= file_is_test;
                        rust_impls.push((file.to_owned(), shape));
                    }
                }
                Some(SourceLang::Go) => {
                    audit.file_count += 1;
                    let Ok(file_decls) =
                        lens_golang::extract_interface_decls_with_module(source, module)
                    else {
                        audit.parse_skipped_file_count += 1;
                        return;
                    };
                    for mut shape in file_decls {
                        shape.is_test |= file_is_test;
                        decls.push(DeclRecord::new(shape, file, "interface"));
                    }
                }
                _ => {}
            }
        })?;

        let mut by_name: HashMap<&str, Vec<usize>> = HashMap::new();
        for (idx, decl) in decls.iter().enumerate() {
            by_name
                .entry(decl.shape.display_name.as_str())
                .or_default()
                .push(idx);
        }
        // Borrow dance: census writes into `decls` while `by_name`
        // borrows the names, so matches are collected first.
        let mut matches: Vec<ImplMatch> = Vec::new();
        for (file, imp) in &rust_impls {
            let Some(slots) = by_name.get(imp.trait_name.as_str()) else {
                continue;
            };
            let implementor = imp.self_type.clone().unwrap_or_else(|| "?".to_owned());
            for &slot in slots {
                if decls[slot].kind != "trait" {
                    continue;
                }
                matches.push(ImplMatch {
                    slot,
                    implementor: implementor.clone(),
                    is_test: imp.is_test,
                    span: Some((file.clone(), imp.span.start_line, imp.span.end_line)),
                });
            }
        }
        for (slot, implementor, is_test) in go_census(graph, &decls) {
            matches.push(ImplMatch {
                slot,
                implementor,
                is_test,
                span: None,
            });
        }
        for m in matches {
            let decl = &mut decls[m.slot];
            if m.is_test {
                decl.test_implementors.insert(m.implementor);
            } else {
                decl.production_implementors.insert(m.implementor);
            }
            decl.allowed.extend(m.span);
        }
        for decl in &mut decls {
            let production = &decl.production_implementors;
            decl.test_implementors
                .retain(|name| !production.contains(name));
        }

        Ok(Self { decls, audit })
    }
}

/// One census hit before it is written back into its declaration.
struct ImplMatch {
    slot: usize,
    implementor: String,
    is_test: bool,
    /// The impl block's `(file, start, end)` for the usage scan's
    /// allowed spans; absent for Go's structural matches, which have no
    /// block.
    span: Option<(String, usize, usize)>,
}

impl DeclRecord {
    fn new(shape: TraitDeclShape, file: &str, kind: &'static str) -> Self {
        let allowed = vec![(file.to_owned(), shape.span.start_line, shape.span.end_line)];
        Self {
            shape,
            file: file.to_owned(),
            kind,
            production_implementors: BTreeSet::new(),
            test_implementors: BTreeSet::new(),
            allowed,
        }
    }
}

/// Structural implementor census for Go: `(decl slot, type name,
/// is_test)` for every in-tree type whose method set covers an
/// interface's methods by name and parameter count. A type counts as a
/// production implementor only when production code supplies every
/// method; a mock in a `_test.go` file satisfies from test scope.
fn go_census(graph: &CallGraph, decls: &[DeclRecord]) -> Vec<(usize, String, bool)> {
    // (module, receiver type) → method name → param counts seen, split
    // by test scope.
    #[derive(Default)]
    struct MethodSet {
        production: BTreeMap<String, BTreeSet<usize>>,
        any: BTreeMap<String, BTreeSet<usize>>,
    }
    let mut types: BTreeMap<(String, String), MethodSet> = BTreeMap::new();
    for node in &graph.nodes {
        if node.graph_language() != Some(GraphLanguage::Go) {
            continue;
        }
        let (Some(owner), Some(param_count)) = (&node.impl_owner, node.param_count) else {
            continue;
        };
        let set = types
            .entry((node.module.clone(), owner.clone()))
            .or_default();
        set.any
            .entry(node.name.clone())
            .or_default()
            .insert(param_count);
        if !node.is_test {
            set.production
                .entry(node.name.clone())
                .or_default()
                .insert(param_count);
        }
    }

    let mut out = Vec::new();
    for (slot, decl) in decls.iter().enumerate() {
        if decl.kind != "interface" || decl.shape.methods.is_empty() {
            continue;
        }
        for ((_, type_name), set) in &types {
            let covers = |methods: &BTreeMap<String, BTreeSet<usize>>| {
                decl.shape.methods.iter().all(|m| {
                    methods
                        .get(&m.name)
                        .is_some_and(|counts| counts.contains(&m.param_count))
                })
            };
            if covers(&set.production) {
                out.push((slot, type_name.clone(), false));
            } else if covers(&set.any) {
                out.push((slot, type_name.clone(), true));
            }
        }
    }
    out
}

/// Bare-name occurrences per judged declaration, outside its allowed
/// spans, with `dyn`-adjacent mentions counted separately.
struct UsageScan {
    /// Keyed by declaration index in [`Inventory::decls`]:
    /// `(references, dyn_references, impl_references)`.
    counts: HashMap<usize, (usize, usize, usize)>,
}

impl UsageScan {
    fn run(
        builder: &CallGraphBuilder,
        roots: &AnalyzeRoots,
        inventory: &Inventory,
    ) -> Result<Self, AnalyzerError> {
        let mut counts: HashMap<usize, (usize, usize, usize)> = HashMap::new();
        let mut slots_by_name: HashMap<&str, Vec<usize>> = HashMap::new();
        let mut allowed_by_file: HashMap<&str, Vec<(usize, usize, usize)>> = HashMap::new();
        for (slot, decl) in inventory.decls.iter().enumerate() {
            if decl.shape.is_test {
                continue;
            }
            slots_by_name
                .entry(decl.shape.display_name.as_str())
                .or_default()
                .push(slot);
            for (file, start, end) in &decl.allowed {
                allowed_by_file
                    .entry(file.as_str())
                    .or_default()
                    .push((*start, *end, slot));
            }
        }
        if slots_by_name.is_empty() {
            return Ok(Self { counts });
        }

        builder.visit_source_texts(roots, |file, source| {
            let allowed = allowed_by_file.get(file).map(Vec::as_slice);
            for (offset, line) in source.lines().enumerate() {
                let line_no = offset + 1;
                let tokens: Vec<&str> = identifiers(line).collect();
                for (position, &token) in tokens.iter().enumerate() {
                    let Some(slots) = slots_by_name.get(token) else {
                        continue;
                    };
                    let is_dyn = position > 0 && tokens[position - 1] == "dyn";
                    // `impl … Name … for …` in raw text is how a macro
                    // body implements a trait; the block extraction
                    // never sees it.
                    let is_impl_pattern = tokens[..position].contains(&"impl")
                        && tokens[position + 1..].contains(&"for");
                    for &slot in slots {
                        let accounted = allowed.is_some_and(|spans| {
                            spans.iter().any(|&(start, end, s)| {
                                s == slot && start <= line_no && line_no <= end
                            })
                        });
                        if accounted {
                            continue;
                        }
                        let entry = counts.entry(slot).or_default();
                        if is_dyn {
                            entry.1 += 1;
                        } else if is_impl_pattern {
                            entry.2 += 1;
                        } else {
                            entry.0 += 1;
                        }
                    }
                }
            }
        })?;
        Ok(Self { counts })
    }
}

impl Report {
    fn build(
        roots: &AnalyzeRoots,
        graph: &CallGraph,
        inventory: Inventory,
        scan: &UsageScan,
    ) -> Self {
        let Inventory { decls, mut audit } = inventory;

        let mut name_counts: HashMap<&str, usize> = HashMap::new();
        for decl in &decls {
            *name_counts
                .entry(decl.shape.display_name.as_str())
                .or_default() += 1;
        }

        let mut distribution = ImplementorDistribution::default();
        let mut declaration_count = 0usize;
        let mut findings = Vec::new();
        for (slot, decl) in decls.iter().enumerate() {
            if decl.shape.is_test {
                audit.test_declaration_count += 1;
                continue;
            }
            if decl.kind == "interface" && decl.shape.methods.is_empty() {
                audit.empty_interface_count += 1;
                continue;
            }
            declaration_count += 1;
            let production = decl.production_implementors.len();
            *match production {
                0 => &mut distribution.zero,
                1 => &mut distribution.one,
                2 => &mut distribution.two,
                _ => &mut distribution.three_plus,
            } += 1;
            if production > 1 {
                continue;
            }

            let &(reference_count, dyn_reference_count, impl_reference_count) =
                scan.counts.get(&slot).unwrap_or(&(0, 0, 0));
            let mut caveats = Vec::new();
            let private = matches!(
                decl.shape.visibility,
                SyntaxFact::Known(VisibilityShape::Private | VisibilityShape::Unexported),
            );
            if !private {
                caveats.push(Caveat::WiderThanPrivate);
            }
            if !decl.test_implementors.is_empty() {
                caveats.push(Caveat::TestImplementors);
            }
            if dyn_reference_count > 0 {
                caveats.push(Caveat::DynDispatch);
            }
            if impl_reference_count > 0 {
                caveats.push(Caveat::MacroImplPattern);
            }
            if name_counts
                .get(decl.shape.display_name.as_str())
                .is_some_and(|&n| n > 1)
            {
                caveats.push(Caveat::SharedName);
            }
            caveats.sort_unstable();

            findings.push(AbstractionEntry {
                kind: decl.kind,
                display_name: decl.shape.display_name.clone(),
                qualified_name: decl.shape.qualified_name.clone(),
                file: decl.file.clone(),
                start_line: decl.shape.span.start_line,
                end_line: decl.shape.span.end_line,
                visibility: NodeVisibility::from_shape(&decl.shape.visibility),
                method_count: decl.shape.methods.len(),
                production_implementors: decl.production_implementors.iter().cloned().collect(),
                test_implementor_count: decl.test_implementors.len(),
                reference_count,
                dyn_reference_count,
                impl_reference_count,
                caveats,
            });
        }

        findings.sort_by(|a, b| {
            a.caveats
                .len()
                .cmp(&b.caveats.len())
                .then_with(|| a.reference_count.cmp(&b.reference_count))
                .then_with(|| a.qualified_name.cmp(&b.qualified_name))
        });

        Self {
            schema_version: SCHEMA_VERSION,
            root: roots.display(),
            language: graph.language,
            note: NOTE,
            audit,
            declaration_count,
            distribution,
            findings,
        }
    }
}

fn format_markdown(report: &Report, top: Option<usize>) -> String {
    let limit = top.unwrap_or(DEFAULT_TOP);
    let (single, zero): (Vec<_>, Vec<_>) = report
        .findings
        .iter()
        .partition(|e| e.production_implementors.len() == 1);
    let mut out = format!(
        "# Single-impl report: {} ({} abstraction(s), {} single-implementation, {} without \
         production implementor)\n",
        report.root,
        report.declaration_count,
        single.len(),
        zero.len(),
    );
    let _ = writeln!(out, "\n{NOTE}\n");
    let _ = writeln!(
        out,
        "Skipped: {} test-scoped declaration(s), {} zero-method interface(s), {} unparsed \
         file(s).",
        report.audit.test_declaration_count,
        report.audit.empty_interface_count,
        report.audit.parse_skipped_file_count,
    );
    if report.declaration_count == 0 {
        out.push_str("\n_No abstractions to analyze._\n");
        return out;
    }

    let _ = writeln!(out, "\n## Single-implementation abstractions (top {limit})");
    out.push_str(
        "\nOne production type implements each. Replace the abstraction with that type, or \
         say what the second implementor will be.\n",
    );
    render_entries(&mut out, &single, limit);

    let _ = writeln!(out, "\n## No production implementor (top {limit})");
    out.push_str(
        "\nNothing in production implements these. With test implementors they are mock-only \
         seams; with none they are either dead or satisfied by types outside the analyzed \
         tree (a Go interface over std types reads this way).\n",
    );
    render_entries(&mut out, &zero, limit);

    let _ = writeln!(out, "\n## Implementor distribution");
    let _ = writeln!(
        out,
        "\nProduction implementors per declaration: 0 → {}, 1 → {}, 2 → {}, 3+ → {}.",
        report.distribution.zero,
        report.distribution.one,
        report.distribution.two,
        report.distribution.three_plus,
    );
    out
}

fn render_entries(out: &mut String, entries: &[&AbstractionEntry], limit: usize) {
    if entries.is_empty() {
        out.push_str("\n_None._\n");
        return;
    }
    out.push('\n');
    for entry in entries.iter().take(limit) {
        let _ = write!(
            out,
            "- `{}` ({}, {}:{}): {} production implementor(s)",
            entry.qualified_name,
            entry.kind,
            entry.file,
            entry.start_line,
            entry.production_implementors.len(),
        );
        if !entry.production_implementors.is_empty() {
            let shown: Vec<String> = entry
                .production_implementors
                .iter()
                .take(IMPLEMENTORS_PER_ROW)
                .map(|name| format!("`{name}`"))
                .collect();
            let _ = write!(out, " ({}", shown.join(", "));
            if entry.production_implementors.len() > IMPLEMENTORS_PER_ROW {
                let _ = write!(
                    out,
                    ", +{}",
                    entry.production_implementors.len() - IMPLEMENTORS_PER_ROW,
                );
            }
            out.push(')');
        }
        if entry.test_implementor_count > 0 {
            let _ = write!(
                out,
                ", +{} test implementor(s)",
                entry.test_implementor_count
            );
        }
        let _ = write!(
            out,
            ", methods={}, refs={}",
            entry.method_count, entry.reference_count,
        );
        if entry.dyn_reference_count > 0 {
            let _ = write!(out, " (dyn {})", entry.dyn_reference_count);
        }
        if entry.impl_reference_count > 0 {
            let _ = write!(out, " (impl-shaped {})", entry.impl_reference_count);
        }
        if !entry.caveats.is_empty() {
            let caveats: Vec<&str> = entry.caveats.iter().map(|c| c.as_str()).collect();
            let _ = write!(out, " — {}", caveats.join("; "));
        }
        out.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::write_file;
    use serde_json::Value;

    fn analyze_json(path: &std::path::Path) -> Value {
        analyze_json_with(path, SingleImplAnalyzer::new())
    }

    fn analyze_json_with(path: &std::path::Path, analyzer: SingleImplAnalyzer) -> Value {
        let json = analyzer.analyze(path, OutputFormat::Json).unwrap();
        serde_json::from_str(&json).unwrap()
    }

    fn finding<'a>(report: &'a Value, name: &str) -> Option<&'a Value> {
        report["findings"]
            .as_array()
            .unwrap()
            .iter()
            .find(|e| e["display_name"] == name)
    }

    #[test]
    fn a_private_trait_with_one_impl_is_a_clean_finding() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store {\n\
                 fn get(&self) -> usize;\n\
             }\n\
             struct Memory;\n\
             impl Store for Memory {\n\
                 fn get(&self) -> usize { 1 }\n\
             }\n\
             pub fn api(s: Memory) -> usize { s.get() }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("Store listed");
        assert_eq!(entry["kind"], "trait");
        assert_eq!(
            entry["production_implementors"],
            serde_json::json!(["Memory"])
        );
        assert_eq!(entry["test_implementor_count"], 0);
        assert_eq!(entry["method_count"], 1);
        assert_eq!(entry["caveats"], serde_json::json!([]));
        assert_eq!(report["distribution"]["one"], 1);
    }

    #[test]
    fn a_two_impl_trait_is_counted_but_not_listed() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct A;\n\
             struct B;\n\
             impl Store for A { fn get(&self) -> usize { 1 } }\n\
             impl Store for B { fn get(&self) -> usize { 2 } }\n",
        );

        let report = analyze_json(dir.path());
        assert!(finding(&report, "Store").is_none());
        assert_eq!(report["distribution"]["two"], 1);
        assert_eq!(report["declaration_count"], 1);
    }

    #[test]
    fn an_out_of_tree_trait_impl_produces_no_row() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "struct Memory;\n\
             impl std::fmt::Display for Memory {\n\
                 fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { Ok(()) }\n\
             }\n",
        );

        let report = analyze_json(dir.path());
        assert_eq!(report["findings"].as_array().unwrap().len(), 0);
        assert_eq!(report["declaration_count"], 0);
    }

    #[test]
    fn a_public_trait_carries_the_visibility_caveat() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "pub trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("listed");
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "wider_than_private"),
            "got {entry:?}",
        );
    }

    #[test]
    fn a_mock_impl_in_test_scope_is_the_mock_seam_caveat() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n\
             #[cfg(test)]\n\
             mod tests {\n\
                 use super::Store;\n\
                 struct Fake;\n\
                 impl Store for Fake { fn get(&self) -> usize { 0 } }\n\
             }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("listed");
        assert_eq!(
            entry["production_implementors"],
            serde_json::json!(["Memory"])
        );
        assert_eq!(entry["test_implementor_count"], 1);
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "test_implementors"),
            "got {entry:?}",
        );
    }

    #[test]
    fn a_dyn_reference_is_counted_and_caveated() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n\
             pub fn boxed() -> Box<dyn Store> { Box::new(Memory) }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("listed");
        assert_eq!(entry["dyn_reference_count"], 1);
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "dyn_dispatch"),
            "got {entry:?}",
        );
    }

    #[test]
    fn references_outside_the_declaration_and_impls_are_counted() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n\
             pub fn generic<S: Store>(s: S) -> usize { s.get() }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("listed");
        // The bound in `generic` is the one mention outside the
        // declaration and the impl block.
        assert_eq!(entry["reference_count"], 1);
        assert_eq!(entry["dyn_reference_count"], 0);
    }

    #[test]
    fn a_macro_generated_impl_line_is_the_macro_caveat() {
        // `macro_rules!` bodies implement traits in text the block
        // extraction never sees, so the count is a lower bound and the
        // row must say so.
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Fancy { fn go(&self); }\n\
             macro_rules! gen {\n\
                 ($ty:ty) => {\n\
                     impl Fancy for $ty {\n\
                         fn go(&self) {}\n\
                     }\n\
                 };\n\
             }\n\
             struct S;\n\
             gen!(S);\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Fancy").expect("listed");
        assert_eq!(entry["production_implementors"], serde_json::json!([]));
        assert_eq!(entry["impl_reference_count"], 1);
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "macro_impl_pattern"),
            "got {entry:?}",
        );
    }

    #[test]
    fn a_trait_with_no_impl_lands_in_the_zero_section() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Unused { fn nothing(&self); }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Unused").expect("listed");
        assert_eq!(entry["production_implementors"], serde_json::json!([]));
        assert_eq!(report["distribution"]["zero"], 1);
    }

    #[test]
    fn a_test_scoped_trait_is_skipped_and_counted() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "pub fn api() {}\n\
             #[cfg(test)]\n\
             mod tests {\n\
                 trait Harness { fn run(&self); }\n\
                 struct H;\n\
                 impl Harness for H { fn run(&self) {} }\n\
             }\n",
        );

        let report = analyze_json(dir.path());
        assert!(finding(&report, "Harness").is_none());
        assert_eq!(report["audit"]["test_declaration_count"], 1);
    }

    #[test]
    fn a_go_interface_with_one_satisfying_type_is_a_finding() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.go",
            "package p\n\n\
             type store interface {\n\
             \tget(id int) int\n\
             }\n\n\
             type memory struct{}\n\n\
             func (m memory) get(id int) int { return id }\n\n\
             type other struct{}\n\n\
             func (o other) unrelated() {}\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "store").expect("store listed");
        assert_eq!(entry["kind"], "interface");
        assert_eq!(
            entry["production_implementors"],
            serde_json::json!(["memory"])
        );
        assert_eq!(entry["caveats"], serde_json::json!([]));
    }

    #[test]
    fn a_go_mock_satisfying_from_a_test_file_is_a_test_implementor() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.go",
            "package p\n\n\
             type store interface {\n\
             \tget(id int) int\n\
             }\n\n\
             type memory struct{}\n\n\
             func (m memory) get(id int) int { return id }\n",
        );
        write_file(
            dir.path(),
            "src/lib_test.go",
            "package p\n\n\
             type fake struct{}\n\n\
             func (f fake) get(id int) int { return 0 }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "store").expect("listed");
        assert_eq!(
            entry["production_implementors"],
            serde_json::json!(["memory"])
        );
        assert_eq!(entry["test_implementor_count"], 1);
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "test_implementors"),
            "got {entry:?}",
        );
    }

    #[test]
    fn a_zero_method_go_interface_is_skipped_and_counted() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.go",
            "package p\n\n\
             type anything interface{}\n\n\
             func Use(a anything) {}\n",
        );

        let report = analyze_json(dir.path());
        assert!(finding(&report, "anything").is_none());
        assert_eq!(report["audit"]["empty_interface_count"], 1);
    }

    #[test]
    fn an_exported_go_interface_carries_the_visibility_caveat() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.go",
            "package p\n\n\
             type Store interface {\n\
             \tGet(id int) int\n\
             }\n\n\
             type memory struct{}\n\n\
             func (m memory) Get(id int) int { return id }\n",
        );

        let report = analyze_json(dir.path());
        let entry = finding(&report, "Store").expect("listed");
        assert!(
            entry["caveats"]
                .as_array()
                .unwrap()
                .iter()
                .any(|c| c == "wider_than_private"),
            "got {entry:?}",
        );
    }

    #[test]
    fn shared_declaration_names_caveat_both_rows() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "mod a { pub trait Codec { fn go(&self); } }\n\
             mod b { pub trait Codec { fn go(&self); } }\n\
             struct X;\n\
             impl a::Codec for X { fn go(&self) {} }\n",
        );

        let report = analyze_json(dir.path());
        let rows: Vec<&Value> = report["findings"]
            .as_array()
            .unwrap()
            .iter()
            .filter(|e| e["display_name"] == "Codec")
            .collect();
        assert_eq!(rows.len(), 2, "got {rows:?}");
        for row in rows {
            assert!(
                row["caveats"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .any(|c| c == "shared_name"),
                "got {row:?}",
            );
            // The one impl attributes to both same-named declarations —
            // inflation, never deflation.
            assert_eq!(row["production_implementors"], serde_json::json!(["X"]));
        }
    }

    #[test]
    fn markdown_renders_sections_distribution_and_caveats() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n\
             trait Unused { fn nothing(&self); }\n",
        );

        let md = SingleImplAnalyzer::new()
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains("# Single-impl report:"), "got: {md}");
        assert!(
            md.contains("## Single-implementation abstractions"),
            "got: {md}",
        );
        assert!(md.contains("## No production implementor"), "got: {md}");
        assert!(md.contains("## Implementor distribution"), "got: {md}");
        assert!(md.contains("`crate::Store`"), "got: {md}");
        assert!(md.contains("(`Memory`)"), "got: {md}");
        assert!(md.contains("`crate::Unused`"), "got: {md}");
        assert!(md.contains("not a verdict"), "got: {md}");
    }

    #[test]
    fn markdown_reports_empty_input_gracefully() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "README.md", "no source here\n");

        let md = SingleImplAnalyzer::new()
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        assert!(md.contains("_No abstractions to analyze._"), "got: {md}");
    }

    #[test]
    fn top_caps_each_markdown_section() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Aa { fn go(&self); }\n\
             trait Bb { fn go(&self); }\n",
        );

        let md = SingleImplAnalyzer::new()
            .with_top(Some(1))
            .analyze(dir.path(), OutputFormat::Md)
            .unwrap();
        // A file with no functions anchors no module, so the qualified
        // name falls back to the bare declaration name.
        assert!(md.contains("top 1"), "got: {md}");
        assert!(md.contains("`Aa`"), "got: {md}");
        assert!(!md.contains("`Bb`"), "got: {md}");
    }

    #[test]
    fn analysis_is_deterministic_across_runs() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait A { fn a(&self); }\n\
             trait B { fn b(&self); }\n\
             struct S;\n\
             impl A for S { fn a(&self) {} }\n\
             impl B for S { fn b(&self) {} }\n",
        );

        let analyzer = SingleImplAnalyzer::new();
        let a = analyzer.analyze(dir.path(), OutputFormat::Json).unwrap();
        let b = analyzer.analyze(dir.path(), OutputFormat::Json).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn exclude_tests_hides_the_mock_seam() {
        let dir = tempfile::tempdir().unwrap();
        write_file(
            dir.path(),
            "src/lib.rs",
            "trait Store { fn get(&self) -> usize; }\n\
             struct Memory;\n\
             impl Store for Memory { fn get(&self) -> usize { 1 } }\n\
             #[cfg(test)]\n\
             mod tests {\n\
                 use super::Store;\n\
                 struct Fake;\n\
                 impl Store for Fake { fn get(&self) -> usize { 0 } }\n\
             }\n",
        );

        let report = analyze_json_with(
            dir.path(),
            SingleImplAnalyzer::new().with_exclude_tests(true),
        );
        let entry = finding(&report, "Store").expect("listed");
        // The cfg(test) impl is still seen by the inventory pass (it
        // parses sources, not the filtered graph), so the seam stays
        // visible even here.
        assert_eq!(entry["test_implementor_count"], 1);
    }
}
