name: Lint Base

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    env:
      MISE_ENV: base
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run pre-commit
        run: prek run --all-files

      - name: lint with mise
        run: mise run lint:base
