name: Lint GHA

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "mise.base.toml"
      - ".github/workflows/lint_gha.yml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "mise.base.toml"
      - ".github/workflows/lint_gha.yml"

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    env:
      MISE_ENV: base
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: lint with mise
        run: mise run lint:gha
