import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      // lcov feeds Codecov (the `web` flag); text keeps the local
      // `mise run test:ts:coverage` run self-explanatory.
      reporter: ["text", "lcov"],
      reportsDirectory: "coverage",
      include: ["src/**/*.ts", "src/**/*.tsx"],
      exclude: [
        "src/**/*.test.ts",
        // Test-only fixture builders; not part of the shipped bundle.
        "src/testSupport.ts",
        // Generated by the TanStack router plugin.
        "src/routeTree.gen.ts",
      ],
    },
  },
});
